# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout

      - run:
          name: Build Docker Image
          command: |
            docker info
            docker build -t bk-nexus .

      - run:
          name: Push to Container Registry
          command: |
            docker login -username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
            docker tag bk-nexus registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web

      - run:
          name: Setup Heroku
          command: |
            chmod +x .circleci/setup-heroku.sh
            .circleci/setup-heroku.sh

      - run:
          name: Deploy to Heroku
          command: |
            heroku container:release web --app $HEROKU_APP_NAME