# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo

    steps:
      - checkout

      - run:
        name: Build Docker Image
        command: docker build -t bk-nexus .

      #- run: 
      #  name: Deploy To Heroku
      #  command: |